import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  String _selectedLang = 'TR'; // Varsayılan dil Türkçe
  
  String get selectedLang => _selectedLang;

  LanguageProvider() {
    _loadLanguage();
  }

  // Kalıcı hafızadan dili yükle
  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _selectedLang = prefs.getString('selected_lang') ?? 'TR';
    notifyListeners();
  }

  // Dili değiştir ve kaydet
  Future<void> setLanguage(String langCode) async {
    _selectedLang = langCode;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('selected_lang', langCode);
  }

  // Çeviri Metinleri
  static final Map<String, Map<String, String>> translations = {
    'TR': {
      'app_name': 'mugut Gelsin',
      'tagline': 'Lezzete Bir Adım Uzaklıktasınız',
      'login_button': 'Giriş Yap',
      'phone_label': 'Telefon Numarası',
      'phone_hint': 'Örn: 5551234567',
      'no_account': 'Hesabınız yok mu?',
      'signup': 'Kayıt Ol',
      'address_select': 'Adres Seçin / Ekle',
      'highlights': 'Öne Çıkanlar',
      'cheapest': 'En Ucuz Lezzetler',
      'restaurants': 'Restoranlar',
      'search_hint': 'Restoran veya yemek arayın...',
      'nav_home': 'Ana Sayfa',
      'nav_favorites': 'Favoriler',
      'nav_cart': 'Sepetim',
      'nav_profile': 'Profil',
      'products': 'Ürünler',
      'no_fav_res': 'Favori restoran bulunamadı!',
      'no_fav_prod': 'Favori ürün bulunamadı!',
      'nav_orders': 'Siparişler',
      'orders': 'Siparişlerim',
      'addresses': 'Adreslerim',
      'payment_methods': 'Ödeme Yöntemlerim',
      'coupons': 'Kuponlarım',
      'help_support': 'Yardım & Destek',
      'mugut_support': 'mugut Destek',
      'logout': 'Çıkış Yap',
      'logout_confirm_title': 'Çıkış Yap',
      'logout_confirm_desc': 'Hesabınızdan çıkış yapmak istediğinize emin misiniz?',
      'clear_cart': 'Sepeti Boşalt',
      'clear_cart_confirm': 'Sepetindeki tüm ürünleri silmek istediğine emin misin?',
      'cancel': 'Vazgeç',
      'clear': 'Boşalt',
      'empty_cart_msg': 'Henüz sepetinde ürün yok!',
      'empty_cart_desc': 'Hemen lezzetli yemeklerden birini seç\nve sepetini doldurmaya başla.',
      'start_shopping': 'Alışverişe Başla',
      'subtotal': 'Ara Toplam',
      'delivery_fee': 'Gönderim Ücreti',
      'service_fee': 'Hizmet Bedeli',
      'total_price': 'Toplam Tutar',
      'complete_order': 'Siparişi Tamamla',
      'register_title': 'Kayıt Ol',
      'create_account': 'Yeni Hesap Oluştur',
      'register_desc': 'Adınızı ve telefon numaranızı girerek kayıt olun.',
      'full_name': 'Ad Soyad',
      'already_have_account': 'Zaten hesabınız var mı?',
      'fill_all_fields': 'Lütfen tüm alanları doldurun',
      'register_success': 'Kayıt başarılı! Giriş yapılıyor...',
      'register_failed': 'Kayıt başarısız',
      'phone_already_registered': 'Bu telefon numarası zaten kayıtlı. Lütfen giriş yapın.',
      'phone_not_registered': 'Bu numara kayıtlı değil. Lütfen önce kayıt olun.',
      'error': 'Hata',
      'add_to_cart': 'Sepete Ekle',
      'quantity': 'Adet',
      'description': 'Açıklama',
      'order_detail': 'Sipariş Detayı',
      'live_track': 'Canlı Takip Et',
      'rate_order': 'Siparişi Puanla',
      'write_review': 'Yorum Yaz',
      'add_address': 'Yeni Adres Ekle',
      'add_card': 'Yeni Kart Ekle',
      'order_tracking': 'Sipariş Takibi',
      'order_placed': 'Sipariş Verildi',
      'preparing': 'Hazırlanıyor',
      'on_the_way': 'Yolda',
      'delivered': 'Teslim Edildi',
      'cancelled': 'İptal Edildi',
      'how_was_it': 'Nasıl Buldunuz?',
      'taste': 'Lezzet',
      'speed': 'Hız',
      'service': 'Servis',
      'send': 'Gönder',
      'later': 'Daha Sonra',
      'order_summary': 'Sipariş Özeti',
      'reorder': 'Siparişi Tekrarla',
      'rated': 'Puanlandı',
      'campaigns': 'Kampanyalar',
      'all_products': 'Tüm Ürünler',
      'order_no': 'Sipariş No',
      'order_received': 'Sipariş Alındı',
      'order_received_desc': 'Siparişiniz dükkana iletildi',
      'preparing_desc': 'Dükkan siparişinizi hazırlıyor',
      'on_the_way_desc': 'Kurye siparişinizi getirmek için yola çıktı',
      'enjoy_meal': 'Afiyet olsun!',
      'now': 'Şu an',
      'delivery_address': 'Teslimat Adresi',
      'connect_support': 'mugut Destek\'e Bağlan',
      'order_note': 'Sipariş Notu',
      'added_to_cart': 'sepete eklendi!',
      'cart_cleared_and_added': 'Sepet boşaltıldı ve ürün eklendi!',
      'shop_closed': 'Restoran Kapalı',
      'shop_closed_warning': 'Bu restoran şu anda kapalıdır. Sipariş veremezsiniz.',
      'different_res_warning': 'Sepetinizde başka bir restorandan ürün var. Sepeti boşaltıp bu ürünü eklemek ister misiniz?',
      'cash_on_delivery': 'Kapıda Nakit',
      'card_on_delivery': 'Kapıda Kredi Kartı',
      'online_payment': 'Uygulama İçi Kredi Kartı',
      'below_min_amount': 'MİNİMUM TUTAR ALTINDA',
      'my_account': 'HESABIM',
      'my_transactions': 'İŞLEMLERİM',
      'help_support_title': 'DESTEK & YARDIM',
      'coupon_hint': 'Kupon Kodun Varsa Gir',
      'apply': 'UYGULA',
      'update': 'GÜNCELLE',
      'discount': 'İndirim',
      'select_address_error': 'Lütfen bir teslimat adresi seçin.',
      'add_payment_error': 'Lütfen bir ödeme yöntemi ekleyin.',
      'enter_phone_error': 'Lütfen bir iletişim numarası girin.',
      'enter_name_error': 'Lütfen adınızı ve soyadınızı girin.',
      'restaurant_reply': 'Restoranın Cevabı',
      'order_again': 'Sipariş Ettiklerin',
      'recommended_for_you': 'Sizin İçin Seçtiklerimiz',
      'most_discovered': 'En Çok Keşfedilenler',
      'top_rated': 'En Yüksek Puanlılar',
      'coupon_applied': 'Kupon Uygulandı!',
      'please_add_address': 'Lütfen bir adres ekleyin',
      'matched_products': 'Eşleşen Ürünler',
      'matched_restaurants': 'Eşleşen Restoranlar',
      'filters': 'Filtrele',
      'delivery_time': 'Teslimat Süresi',
      'rating': 'Puan',
      'cuisine': 'Mutfak',
      'distance': 'Mesafe',
      'distance_filter_title': 'Maksimum Teslimat Mesafesi',
      'distance_filter_desc': 'Seçilen mesafenin ötesindeki dükkanlar gösterilmeyecektir.',
      'max_distance_label': 'Maksimum Mesafe: {dist} km',
      'distance_km': '{dist} km',
      'apply_filter': 'Filtreyi Uygula',
      'no_restaurants_in_range': 'Bu mesafede restoran bulunamadı. Mesafeyi artırmayı deneyin.',
      'all': 'Hepsi',
      'in_arzan': 'En Ucuz',
      'burger': 'Burger',
      'pizza': 'Pizza',
      'kebab': 'Kebap',
      'dessert': 'Tatlı',
      'seafood': 'Deniz Ürünü',
      'drink': 'İçecek',
      'min_order_warning': 'Minimum sipariş tutarı {min} TMT\'dir. Sipariş vermek için sepetinize {rem} TMT\'lik ürün daha ekleyin.',
      'fav_empty_msg': 'Favorilerine eklediklerin burada görünecek.',
      'different_res_title': 'Farklı Restoran?',
      'different_res_msg': 'Sepetinizde zaten \'{res}\' restoranından ürünler var. Mevcut sepeti boşaltıp \'{newRes}\' restoranından yeni bir sipariş başlatmak istiyor musunuz?',
      'give_up': 'Vazgeç',
      'clear_cart_and_add': 'Sepeti Boşalt ve Ekle',
      'code_sent_msg': 'Doğrulama kodu gönderildi.',
      'enter_code_error': 'Lütfen doğrulama kodunu girin.',
      'verify_code': 'Kodu Doğrula',
      'sms_sent_to': '{phone} numarasına bir SMS kodu gönderdik.',
      'verify_and_register': 'DOĞRULA VE KAYIT OL',
      'unknown_customer': 'Bilinmeyen Müşteri',
      'unnamed_shop': 'İsimsiz Dükkan',
      'tagline_splash': 'Lezzet Kapınızda',
      'review_thanks': 'Değerlendirmeniz için teşekkürler!',
      'error_occurred': 'Hata oluştu: {error}',
      'rate': 'Değerlendir',
      'how_was_order': 'Siparişinizi nasıl buldunuz?',
      'invalid_coupon': 'Geçersiz veya bu restorana ait olmayan kupon kodu.',
      'campaign_label': 'KAMPANYA',
      'coupon_code_label': 'KUPON KODU',
      'special_offer_label': 'ÖZEL FIRSAT',
      'code_label': 'KOD',
      'banner_1_title': 'Gurme Burgerler',
      'banner_1_desc': '%20 İndirim Fırsatını Kaçırmayın!',
      'banner_2_title': 'Sıcak Pizzalar',
      'banner_2_desc': 'İkinci Pizzada %50 İndirim!',
      'banner_3_title': 'Taze Suşiler',
      'banner_3_desc': 'Uzak Doğu Esintisi Kapınızda.',
      'banner_4_title': 'İtalyan Makarnaları',
      'banner_4_desc': 'Gerçek İtalyan Lezzeti.',
      'banner_5_title': 'Efsane Tatlılar',
      'banner_5_desc': 'Gününüzü Tatlandırın.',
      'banner_6_title': 'Taze Salatalar',
      'banner_6_desc': 'Sağlıklı ve Hafif Seçenekler.',
      'banner_7_title': 'Zengin Kahvaltı',
      'banner_7_desc': 'Güne Güzel Bir Başlangıç Yapın.',
      'banner_8_title': 'Nisbet Kebap',
      'banner_8_desc': 'Gerçek Kebap Keyfi Burada.',
      'banner_9_title': 'Serinleten Dondurma',
      'banner_9_desc': 'Her Mevsim Ferahlık.',
      'banner_10_title': 'Özel Kahveler',
      'banner_10_desc': 'Kahve Molanız Keyfe Dönüşsün.',
      'city_label': 'Şehir (Welaýat)',
      'district_label': 'İlçe (Etrap)',
      'select_city': 'Şehir seçin',
      'select_district': 'İlçe seçin',
      'select_region_title': 'Lütfen Bölgenizi Seçin',
      'select_region_desc': 'Size en yakın restoranları gösterebilmemiz için bölgenizi seçmelisiniz.',
    },
    'TM': {
      'app_name': 'mugut Gelsin',
      'tagline': 'Tagama Bir Ädim Galdyňyz',
      'login_button': 'Giriş Et',
      'phone_label': 'Telefon Belgisi',
      'phone_hint': 'Meselem: 65123456',
      'no_account': 'Hasabyňyz ýokmy?',
      'signup': 'Hasap Aç',
      'address_select': 'Adres Saýlaň / Goşuň',
      'highlights': 'Möhüm we Meşhur',
      'cheapest': 'Iň Arzan Tagamlar',
      'restaurants': 'Restoranlar',
      'search_hint': 'Restoran ýa-da tagam gözläň...',
      'nav_home': 'Baş Sahypa',
      'nav_favorites': 'Halanlarym',
      'nav_cart': 'Sebedim',
      'nav_profile': 'Profilim',
      'products': 'Önümler',
      'no_fav_res': 'Halanýan restoran tapylmady!',
      'no_fav_prod': 'Halanýan önüm tapylmady!',
      'nav_orders': 'Sargytlar',
      'orders': 'Sargytlarym',
      'addresses': 'Adreslerim',
      'payment_methods': 'Töleg usullarym',
      'coupons': 'Kuponlarym',
      'help_support': 'Kömek we Goldaw',
      'mugut_support': 'mugut Goldaw',
      'logout': 'Hasapdan çyk',
      'logout_confirm_title': 'Hasapdan çyk',
      'logout_confirm_desc': 'Hasabyňyzdan çykmak isleýändigiňize ynanýarsyňyzmy?',
      'clear_cart': 'Sebedi boşat',
      'clear_cart_confirm': 'Sebediňizdäki ähli önümleri pozmak isleýändigiňize ynanýarsyňyzmy?',
      'cancel': 'Bes et',
      'clear': 'Poz',
      'empty_cart_msg': 'Sebediňizde entek önüm ýok!',
      'empty_cart_desc': 'Häzir lezzetli tagamlaryň birini saýlaň\nwe sebediňizi doldurmaga başlaň.',
      'start_shopping': 'Söwda başla',
      'subtotal': 'Jemi',
      'delivery_fee': 'Eltip bermek tölegi',
      'service_fee': 'Hyzmat tölegi',
      'total_price': 'Umumy baha',
      'complete_order': 'Sargydy tamamla',
      'register_title': 'Hasap Aç',
      'create_account': 'Täze Hasap Döret',
      'register_desc': 'Adyňyzy we telefon belgiňizi girizip hasap açyň.',
      'full_name': 'Adyňyz we Familiýaňyz',
      'already_have_account': 'Hasabyňyz barmy?',
      'fill_all_fields': 'Ehlisini dolduryň!',
      'register_success': 'Hasap açyldy! Giriş edilýär...',
      'register_failed': 'Hasap açylmady',
      'phone_already_registered': 'Bu telefon belgisi eýýäm hasaba alnan.',
      'phone_not_registered': 'Bu telefon belgisi hasaba alynmadyk. Ilki bilen hasap açyň.',
      'error': 'Säwlik',
      'add_to_cart': 'Sebede goş',
      'quantity': 'Sany',
      'description': 'Düşündiriş',
      'order_detail': 'Sargyt maglumatlary',
      'live_track': 'Canly yzarla',
      'rate_order': 'Sargydy bahalandyr',
      'write_review': 'Teswir ýaz',
      'add_address': 'Täze adres goş',
      'add_card': 'Täze kart goş',
      'order_tracking': 'Sargyt yzarlamak',
      'order_placed': 'Sargyt edildi',
      'preparing': 'Taýýarlanýar',
      'on_the_way': 'Ýolda',
      'delivered': 'Eltildi',
      'cancelled': 'Bes edildi',
      'how_was_it': 'Nähili tapdyňyz?',
      'taste': 'Tagamy',
      'speed': 'Tizligi',
      'service': 'Hyzmaty',
      'send': 'Iber',
      'later': 'Soňrak',
      'order_summary': 'Sargyt jemi',
      'reorder': 'Sargydy gaýtala',
      'rated': 'Bahalandyryldy',
      'campaigns': 'Aksiýalar',
      'all_products': 'Ähli önümler',
      'order_no': 'Sargyt No',
      'order_received': 'Sargyt alyndy',
      'order_received_desc': 'Sargydyňyz dükana ýetirildi',
      'preparing_desc': 'Dükanda sargydyňyz taýýarlanýar',
      'on_the_way_desc': 'Kuryer sargydyňyzy eltip bermek üçin ýola çykdy',
      'enjoy_meal': 'Işdäňiz açyk bolsun!',
      'now': 'Şu wagt',
      'delivery_address': 'Eltip bermeli adres',
      'connect_support': 'mugut Goldawa baglan',
      'order_note': 'Sargyt belgi',
      'added_to_cart': 'sebede goşuldy!',
      'cart_cleared_and_added': 'Sebet boşadyldy we önüm goşuldy!',
      'shop_closed': 'Restoran ýapyk',
      'shop_closed_warning': 'Bu restoran häzirki wagtda ýapyk. Sargyt edip bilmersiňiz.',
      'different_res_warning': 'Sebediňizde başga restoranyň önümi bar. Sebedi boşadyp, bu önümi goşmak isleýärsiňizmi?',
      'cash_on_delivery': 'Gapıda Nagyt',
      'card_on_delivery': 'Gapıda Kredi Karty',
      'online_payment': 'Onlaýn Töleg',
      'below_min_amount': 'MINIMUM BAHADAN AZ',
      'my_account': 'HASABYM',
      'my_transactions': 'AMALLARYM',
      'help_support_title': 'GOLDAW WE KÖMEK',
      'no_address': 'Entek hasaba alnan adresiňiz ýok.',
      'add_first_address': 'ILKINJI ADRESIŇI GOŞ',
      'default': 'ESASY',
      'delete_address': 'Adresi poz',
      'delete_confirm': 'Bu adresi pozmak isleýändigiňize ynanýarsyňyzmy?',
      'coupon_hint': 'Kupon kodyňyz bar bolsa giriziň',
      'apply': 'ULAN',
      'update': 'TÄZELE',
      'discount': 'Arzanladyş',
      'select_address_error': 'Eltip bermeli adresi saýlaň.',
      'add_payment_error': 'Töleg usulyny goşuň.',
      'enter_phone_error': 'Habarlaşmak üçin telefon belgiňizi giriziň.',
      'enter_name_error': 'Adyňyzy we familiýaňyzy giriziň.',
      'restaurant_reply': 'Restoranyň jogaby',
      'order_again': 'Sargyt Edenleriňiz',
      'recommended_for_you': 'Siziň Üçin Saýlanlarymyz',
      'most_discovered': 'Iň Köp Açyş Edilenler',
      'top_rated': 'Iň Ýokary Bahalylar',
      'coupon_applied': 'Kupon ulandyldy!',
      'please_add_address': 'Adres goşuň',
      'matched_products': 'Gabat gelen önümler',
      'matched_restaurants': 'Gabat gelen restoranlar',
      'filters': 'Süzgüç',
      'delivery_time': 'Eltip berme wagty',
      'rating': 'Bahalandyrma',
      'cuisine': 'Aşhana',
      'all': 'Ählisi',
      'in_arzan': 'Iň Arzan',
      'burger': 'Burger',
      'pizza': 'Pissa',
      'kebab': 'Kebap',
      'dessert': 'Süýjülikler',
      'seafood': 'Deňiz önümleri',
      'drink': 'Içgiler',
      'min_order_warning': 'Minimum sargyt bahasy {min} TMT. Sargyt etmek üçin sebediňize ýene {rem} TMT önüm goşuň.',
      'fav_empty_msg': 'Halanlaryňyza goşanlaryňyz bu ýerde görner.',
      'different_res_title': 'Başga restoran?',
      'different_res_msg': 'Sebediňizde eýýäm \'{res}\' restoranynyň önümleri bar. Bar bolan sebedi boşadyp, \'{newRes}\' restoranyndan täze sargyt başlamak isleýärsiňizmi?',
      'give_up': 'Bes et',
      'clear_cart_and_add': 'Sebedi boşat we goş',
      'code_sent_msg': 'Tassyklama kody iberildi.',
      'enter_code_error': 'Lütfen tassyklama koduny giriziň.',
      'verify_code': 'Koduny tassyklamak',
      'sms_sent_to': '{phone} belgisine SMS kody iberdik.',
      'verify_and_register': 'TASSYKLAMAK WE HASAP AÇMAK',
      'unknown_customer': 'Nätanyş müşderi',
      'unnamed_shop': 'Atsyz dükan',
      'tagline_splash': 'Lezzet Gapyňyzda',
      'review_thanks': 'Bahalandyrmaňyz üçin sag boluň!',
      'error_occurred': 'Säwlik ýüze çykdy: {error}',
      'rate': 'Bahalandyr',
      'how_was_order': 'Sargydyňyzy nähili tapdyňyz?',
      'invalid_coupon': 'Kupon kody nädogry ýa-da bu restorana degişli däl.',
      'campaign_label': 'KAMPANIÝA',
      'coupon_code_label': 'KUPON KODY',
      'special_offer_label': 'ÝÖRITE TEKLIP',
      'code_label': 'KOD',
      'banner_1_title': 'Gurme Burgerler',
      'banner_1_desc': '%20 Arzanladyş Pursatyny Elden Gidirmäň!',
      'banner_2_title': 'Gyzgyn Pizzalar',
      'banner_2_desc': 'Ikinji Pizzada %50 Arzanladyş!',
      'banner_3_title': 'Täze Suşiler',
      'banner_3_desc': 'Uzak Gündogar Lezzeti Gapyňyzda.',
      'banner_4_title': 'Italýan Makaronlary',
      'banner_4_desc': 'Hakyky Italýan Tagamy.',
      'banner_5_title': 'Efsana Süýtli Tagamlar',
      'banner_5_desc': 'Günüňizi Süýjediň.',
      'banner_6_title': 'Täze Salatlar',
      'banner_6_desc': 'Sagdyn we Ýeňil Seçenekler.',
      'banner_7_title': 'Baý Ertirlik',
      'banner_7_desc': 'Güne Gowy Başlangyç Ediň.',
      'banner_8_title': 'Nisbet Kebap',
      'banner_8_desc': 'Hakyky Kebap Lezzeti Bu Ýerde.',
      'banner_9_title': 'Sowadyjy Doňdurma',
      'banner_9_desc': 'Her möwsümde serginlik.',
      'banner_10_title': 'Ýörite Kofeler',
      'banner_10_desc': 'Kofe arakesmäňiz lezzete öwrülsün.',
      'city_label': 'Welaýat',
      'district_label': 'Etrap',
      'select_city': 'Welaýat saýlaň',
      'select_district': 'Etrap saýlaň',
      'select_region_title': 'Haýyş ýaşaýan welaýatyňyzy saýlaň',
      'select_region_desc': 'Size iň golaý restoranlary görkezmegimiz üçin welaýatyňyzy saýlamalysyňyz.',
      'distance': 'Aralyk',
      'distance_filter_title': 'Iň Uly Eltip Beriş Aralygy',
      'distance_filter_desc': 'Saýlanan aralykdan uzakdaky dükkanlar görünmez.',
      'max_distance_label': 'Iň Uly Aralyk: {dist} km',
      'distance_km': '{dist} km',
      'apply_filter': 'Filtri Ullan',
      'no_restaurants_in_range': 'Bu aralykda restoran tapylmady. Aralygy artdyrmaga synanyşyň.',
    },
    'RU': {
      'app_name': 'mugut Gelsin',
      'tagline': 'Вы в одном шаге от вкуса',
      'login_button': 'Войти',
      'phone_label': 'Номер телефона',
      'phone_hint': 'Прим: 5551234567',
      'no_account': 'Нет аккаунта?',
      'signup': 'Регистрация',
      'address_select': 'Выбрать / Добавить адрес',
      'highlights': 'Рекомендуемое',
      'cheapest': 'Самые дешевые блюда',
      'restaurants': 'Рестораны',
      'search_hint': 'Поиск ресторанов или еды...',
      'nav_home': 'Главная',
      'nav_favorites': 'Избранное',
      'nav_cart': 'Корзина',
      'nav_profile': 'Профиль',
      'products': 'Продукты',
      'no_fav_res': 'Любимых ресторанов не найдено!',
      'no_fav_prod': 'Любимых продуктов не найдено!',
      'nav_orders': 'Заказы',
      'orders': 'Мои заказы',
      'addresses': 'Мои адреса',
      'payment_methods': 'Способы оплаты',
      'coupons': 'Мои купоны',
      'help_support': 'Помощь и поддержка',
      'mugut_support': 'Мугт поддержка',
      'logout': 'Выйти',
      'logout_confirm_title': 'Выход',
      'logout_confirm_desc': 'Вы уверены, что хотите выйти из своего аккаунта?',
      'clear_cart': 'Очистить корзину',
      'clear_cart_confirm': 'Вы уверены, что хотите удалить все товары из корзины?',
      'cancel': 'Отмена',
      'clear': 'Очистить',
      'empty_cart_msg': 'В вашей корзине пока нет товаров!',
      'empty_cart_desc': 'Выберите одно из вкусных блюд прямо сейчас\nand начните наполнять свою корзину.',
      'start_shopping': 'Начать покупки',
      'subtotal': 'Подытог',
      'delivery_fee': 'Стоимость доставки',
      'service_fee': 'Сервисный сбор',
      'total_price': 'Итоговая сумма',
      'complete_order': 'Оформить заказ',
      'register_title': 'Регистрация',
      'create_account': 'Создать аккаунт',
      'register_desc': 'Зарегистрируйтесь, введя свое имя и номер телефона.',
      'full_name': 'Имя и Фамилия',
      'already_have_account': 'Уже есть аккаунт?',
      'fill_all_fields': 'Пожалуйста, заполните все поля',
      'register_success': 'Регистрация прошла успешно!',
      'register_failed': 'Ошибка регистрации',
      'phone_already_registered': 'Этот номер уже зарегистрирован. Пожалуйста, войдите.',
      'phone_not_registered': 'Этот номер не зарегистрирован. Пожалуйста, сначала зарегистрируйтесь.',
      'error': 'Ошибка',
      'add_to_cart': 'В корзину',
      'quantity': 'Кол-во',
      'description': 'Описание',
      'order_detail': 'Детали заказа',
      'live_track': 'Отследить',
      'rate_order': 'Оценить заказ',
      'write_review': 'Написать отзыв',
      'add_address': 'Добавить адрес',
      'add_card': 'Добавить карту',
      'order_tracking': 'Отслеживание заказа',
      'order_placed': 'Заказ размещен',
      'preparing': 'Готовится',
      'on_the_way': 'В пути',
      'delivered': 'Доставлено',
      'cancelled': 'Отменено',
      'how_was_it': 'Как вам заказ?',
      'taste': 'Вкус',
      'speed': 'Скорость',
      'service': 'Сервис',
      'send': 'Отправить',
      'later': 'Позже',
      'order_summary': 'Сводка заказа',
      'reorder': 'Повторить заказ',
      'rated': 'Оценено',
      'campaigns': 'Акции',
      'all_products': 'Все продукты',
      'order_no': 'Заказ №',
      'order_received': 'Заказ получен',
      'order_received_desc': 'Ваш заказ передан в магазин',
      'preparing_desc': 'Магазин готовит ваш заказ',
      'on_the_way_desc': 'Курьер уже в пути с вашим заказом',
      'enjoy_meal': 'Приятного аппетита!',
      'now': 'Сейчас',
      'delivery_address': 'Адрес доставки',
      'connect_support': 'Связаться с поддержкой',
      'order_note': 'Примечание к заказу',
      'added_to_cart': 'добавлено в корзину!',
      'cart_cleared_and_added': 'Корзина очищена и товар добавлен!',
      'shop_closed': 'Ресторан закрыт',
      'shop_closed_warning': 'Этот ресторан сейчас закрыт. Вы не можете сделать заказ.',
      'different_res_warning': 'В вашей корзине есть товары из другого ресторана. Хотите очистить корзину и добавить этот товар?',
      'cash_on_delivery': 'Наличными при получении',
      'card_on_delivery': 'Картой при получении',
      'online_payment': 'Онлайн оплата',
      'below_min_amount': 'НИЖЕ МИНИМУМА',
      'my_account': 'МОЙ АККАУНТ',
      'my_transactions': 'МОИ ОПЕРАЦИИ',
      'help_support_title': 'ПОДДЕРЖКА И ПОМОЩЬ',
      'no_address': 'У вас пока нет сохраненных адресов.',
      'add_first_address': 'ДОБАВИТЬ ПЕРВЫЙ АДРЕС',
      'default': 'ПО УМОЛЧАНИЮ',
      'delete_address': 'Удалить адрес',
      'delete_confirm': 'Вы уверены, что хотите удалить этот адрес?',
      'coupon_hint': 'Введите промокод',
      'apply': 'ПРИМЕНИТЬ',
      'update': 'ОБНОВИТЬ',
      'discount': 'Скидка',
      'select_address_error': 'Пожалуйста, выберите адрес доставки.',
      'add_payment_error': 'Пожалуйста, добавьте способ оплаты.',
      'enter_phone_error': 'Пожалуйста, введите контактный номер.',
      'enter_name_error': 'Пожалуйста, введите имя и фамилию.',
      'restaurant_reply': 'Ответ ресторана',
      'order_again': 'Ваши заказы',
      'recommended_for_you': 'Рекомендуем вам',
      'most_discovered': 'Самые популярные',
      'top_rated': 'Лучшие по рейтингу',
      'coupon_applied': 'Купон применен!',
      'please_add_address': 'Пожалуйста, добавьте адрес',
      'matched_products': 'Найденные продукты',
      'matched_restaurants': 'Найденные рестораны',
      'filters': 'Фильтры',
      'delivery_time': 'Время доставки',
      'rating': 'Рейтинг',
      'cuisine': 'Кухня',
      'all': 'Все',
      'in_arzan': 'Дешевые',
      'burger': 'Бургер',
      'pizza': 'Пицца',
      'kebab': 'Кебаб',
      'dessert': 'Десерты',
      'seafood': 'Морепродукты',
      'drink': 'Напитки',
      'min_order_warning': 'Минимальная сумма заказа {min} TMT. Добавьте еще товаров на {rem} TMT.',
      'fav_empty_msg': 'Здесь будут отображаться товары, добавленные в избранное.',
      'different_res_title': 'Другой ресторан?',
      'different_res_msg': 'В вашей корзине уже есть товары из ресторана \'{res}\'. Хотите очистить корзину и начать новый заказ в \'{newRes}\'?',
      'give_up': 'Отмена',
      'clear_cart_and_add': 'Очистить и добавить',
      'code_sent_msg': 'Код подтверждения отправлен.',
      'enter_code_error': 'Пожалуйста, введите код подтверждения.',
      'verify_code': 'Подтвердить код',
      'sms_sent_to': 'Мы отправили SMS-код на номер {phone}.',
      'verify_and_register': 'ПОДТВЕРДИТЬ И ЗАРЕГИСТРИРОВАТЬСЯ',
      'unknown_customer': 'Неизвестный клиент',
      'unnamed_shop': 'Магазин без названия',
      'tagline_splash': 'Вкус у ваших дверей',
      'review_thanks': 'Спасибо за ваш отзыв!',
      'error_occurred': 'Произошла ошибка: {error}',
      'rate': 'Оценить',
      'how_was_order': 'Как вам ваш заказ?',
      'invalid_coupon': 'Промокод недействителен или не принадлежит этому ресторану.',
      'campaign_label': 'АКЦИЯ',
      'coupon_code_label': 'ПРОМОКОД',
      'special_offer_label': 'СПЕЦПРЕДЛОЖЕНИЕ',
      'code_label': 'КОД',
      'banner_1_title': 'Гурме Бургеры',
      'banner_1_desc': 'Не пропустите скидку 20%!',
      'banner_2_title': 'Горячая Пицца',
      'banner_2_desc': 'Скидка 50% на вторую пиццу!',
      'banner_3_title': 'Свежие Суши',
      'banner_3_desc': 'Вкус Дальнего Востока у ваших дверей.',
      'banner_4_title': 'Итальянская Паста',
      'banner_4_desc': 'Настоящий итальянский вкус.',
      'banner_5_title': 'Легендарные Десерты',
      'banner_5_desc': 'Подсластите свой день.',
      'banner_6_title': 'Свежие Салаты',
      'banner_6_desc': 'Здоровый и легкий выбор.',
      'banner_7_title': 'Богатый Завтрак',
      'banner_7_desc': 'Начните день красиво.',
      'banner_8_title': 'Нисбет Кебаб',
      'banner_8_desc': 'Настоящий вкус кебаба здесь.',
      'banner_9_title': 'Освежающее Мороженое',
      'banner_9_desc': 'Свежесть в любой сезон.',
      'banner_10_title': 'Особый кофе',
      'banner_10_desc': 'Превратите перерыв на кофе в удовольствие.',
      'city_label': 'Город (Велаят)',
      'district_label': 'Район (Этрап)',
      'select_city': 'Выберите город',
      'select_district': 'Выберите район',
      'select_region_title': 'Пожалуйста, выберите ваш регион',
      'select_region_desc': 'Вам необходимо выбрать свой регион, чтобы мы могли показать ближайшие к вам рестораны.',
      'distance': 'Расстояние',
      'distance_filter_title': 'Макс. Расстояние Доставки',
      'distance_filter_desc': 'Заведения дальше выбранного расстояния не будут показаны.',
      'max_distance_label': 'Макс. расстояние: {dist} км',
      'distance_km': '{dist} км',
      'apply_filter': 'Применить фильтр',
      'no_restaurants_in_range': 'Рестораны в этом радиусе не найдены. Попробуйте увеличить расстояние.',
    },
  };

  String translate(String key) {
    return translations[_selectedLang]?[key] ?? key;
  }

  // Alias for translate
  String get(String key) => translate(key);
}

