// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0p9dXFHuA4ST96QrQA7LuRE7qCBhq6Uo',
    appId: '1:244575841502:web:4b9d3d4422f6884b4de64f',
    messagingSenderId: '244575841502',
    projectId: 'getir-clone-b8568',
    authDomain: 'getir-clone-b8568.firebaseapp.com',
    storageBucket: 'getir-clone-b8568.firebasestorage.app',
    measurementId: 'G-ZNKXPTDBZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DMj6MbWH9vtugG5Nb5gdXGcni4dyuWo',
    appId: '1:244575841502:android:f9569fe4bfcf04f84de64f',
    messagingSenderId: '244575841502',
    projectId: 'getir-clone-b8568',
    storageBucket: 'getir-clone-b8568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWr57hg6m0pGBFxnx8BNuN9y4L9uf5YOo',
    appId: '1:244575841502:ios:688aba74ad6d584f4de64f',
    messagingSenderId: '244575841502',
    projectId: 'getir-clone-b8568',
    storageBucket: 'getir-clone-b8568.firebasestorage.app',
    iosBundleId: 'com.example.mugtGelsin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWr57hg6m0pGBFxnx8BNuN9y4L9uf5YOo',
    appId: '1:244575841502:ios:688aba74ad6d584f4de64f',
    messagingSenderId: '244575841502',
    projectId: 'getir-clone-b8568',
    storageBucket: 'getir-clone-b8568.firebasestorage.app',
    iosBundleId: 'com.example.mugtGelsin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0p9dXFHuA4ST96QrQA7LuRE7qCBhq6Uo',
    appId: '1:244575841502:web:6df56e92065e1cc14de64f',
    messagingSenderId: '244575841502',
    projectId: 'getir-clone-b8568',
    authDomain: 'getir-clone-b8568.firebaseapp.com',
    storageBucket: 'getir-clone-b8568.firebasestorage.app',
    measurementId: 'G-12185JTF5W',
  );

}