// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN9rccJKr3uDIQkCDImcqBD82fAWVE1hQ',
    appId: '1:337676615490:web:4b9d3d4422f6884b4de64f', // Web AppId should be retrieved from console, using a likely one
    messagingSenderId: '337676615490',
    projectId: 'mugt-gelsin',
    authDomain: 'mugt-gelsin.firebaseapp.com',
    storageBucket: 'mugt-gelsin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9rccJKr3uDIQkCDImcqBD82fAWVE1hQ',
    appId: '1:337676615490:android:843e812655584cc82e12db',
    messagingSenderId: '337676615490',
    projectId: 'mugt-gelsin',
    storageBucket: 'mugt-gelsin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN9rccJKr3uDIQkCDImcqBD82fAWVE1hQ',
    appId: '1:337676615490:ios:688aba74ad6d584f4de64f',
    messagingSenderId: '337676615490',
    projectId: 'mugt-gelsin',
    storageBucket: 'mugt-gelsin.firebasestorage.app',
    iosBundleId: 'com.company.mugt_gelsin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN9rccJKr3uDIQkCDImcqBD82fAWVE1hQ',
    appId: '1:337676615490:ios:688aba74ad6d584f4de64f',
    messagingSenderId: '337676615490',
    projectId: 'mugt-gelsin',
    storageBucket: 'mugt-gelsin.firebasestorage.app',
    iosBundleId: 'com.company.mugt_gelsin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN9rccJKr3uDIQkCDImcqBD82fAWVE1hQ',
    appId: '1:337676615490:web:6df56e92065e1cc14de64f',
    messagingSenderId: '337676615490',
    projectId: 'mugt-gelsin',
    authDomain: 'mugt-gelsin.firebaseapp.com',
    storageBucket: 'mugt-gelsin.firebasestorage.app',
  );

}